### ISSUE TITLE
It seems like repo needs requirements.text or something like this

### ISSUE THREAD

**Issue by ceoworks** [nevenp/dqn_flappy_bird#2]
Try to run `python dqn.py test` after cloning repo gives error:

```
File "dqn.py", line 1, in <module>
    import cv2
```

**Comment by nevenp** [comment]
OpenCV is also dependency. I forgot to list it in dependencies. Install it and it should work.

**Comment by ceoworks** [comment]
thanks a lot, pretrained model worked fine for me, but a couple of suggestions to consider:

- it would be great not only specify dependencies, but also write command to install all of them `pip3 install pygame torch opencv-python` in README

- I encountered exception `RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.` and changing the line `235` to `model = torch.load('pretrained_model/current_model_2000000.pth', map_location='cpu').eval()` worked for me, hope it helps somebody

**Comment by nevenp** [comment]
I added requirements.txt file to install all dependencies.

I updated the code to enable loading of pretrained model on the CPU.

Thank you!
